name: flutter_my_demo_project
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  fluttertoast: ^8.2.1
  flutter_datetime_picker: ^1.5.1
  simple_animations: ^5.0.1
  sqflite: ^2.2.8+4
  path_provider: ^2.0.15
  connectivity_plus: ^5.0.1
  http: ^0.13.6
  shared_preferences: ^2.2.2
  image_picker: ^1.0.4
  firebase_messaging: ^14.6.1
  firebase_core: ^2.13.0
  flutter_local_notifications: ^14.1.0
  razorpay_flutter: ^1.3.5
  rive: ^0.9.1
  flutter_svg: ^1.1.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/avaters/
    - assets/Backgrounds/
    - assets/icons/
    - assets/RiveAssets/

  fonts:
    - family: Intel
      fonts:
        - asset: assets/Fonts/Inter-Regular.ttf
        - asset: assets/Fonts/Inter-SemiBold.ttf
          weight: 600
    - family: Poppins
      fonts:
        - asset: assets/Fonts/Poppins-Bold.ttf
          weight: 700